import { StatItem, Course, NavItem, Assignment, NotificationItem, StudentProfile } from './types';

export const STUDENT: StudentProfile = {
  name: 'Hoàng Thị Hòa',
  studentId: 'B23DCCC069',
  class: 'D23CQCN01-B',
  major: 'Công nghệ thông tin',
  faculty: 'Khoa Công nghệ Thông tin 1',
  school: 'Học viện Công nghệ Bưu chính Viễn thông (PTIT)',
  email: 'B23DCCC069@stu.ptit.edu.vn',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  gpa: 3.68,
  completedCredits: 45,
  totalCredits: 135,
  academicYear: '2023 - 2027',
};

export const COURSES: Course[] = [
  {
    id: '1',
    name: 'Lập trình React Native',
    code: 'INT1434',
    credits: 3,
    instructor: 'TS. Nguyễn Mạnh Hùng',
    schedule: 'Thứ 2 (07:00 - 09:30)',
    room: 'P.302-A2 (Hà Đông)',
    icon: 'code',
    lessons: 24,
    completedLessons: 18,
    progress: 0.75,
    color: '#4F46E5',
    category: 'Chuyên ngành',
  },
  {
    id: '2',
    name: 'Cơ sở dữ liệu',
    code: 'INT1154',
    credits: 3,
    instructor: 'TS. Hoàng Xuân Dậu',
    schedule: 'Thứ 4 (09:45 - 12:00)',
    room: 'P.201-A3 (Hà Đông)',
    icon: 'database',
    lessons: 18,
    completedLessons: 18,
    progress: 1.0,
    color: '#059669',
    category: 'Cơ sở ngành',
  },
  {
    id: '3',
    name: 'Cấu trúc dữ liệu & Giải thuật',
    code: 'INT1340',
    credits: 3,
    instructor: 'ThS. Trần Thị Mai',
    schedule: 'Thứ 3 (13:00 - 15:30)',
    room: 'P.405-A2 (Hà Đông)',
    icon: 'algo',
    lessons: 30,
    completedLessons: 12,
    progress: 0.4,
    color: '#7C3AED',
    category: 'Cơ sở ngành',
  },
  {
    id: '4',
    name: 'Lập trình Java nâng cao',
    code: 'INT1332',
    credits: 3,
    instructor: 'TS. Lê Văn Tuấn',
    schedule: 'Thứ 6 (07:00 - 09:30)',
    room: 'P.102-A2 (Hà Đông)',
    icon: 'java',
    lessons: 20,
    completedLessons: 2,
    progress: 0.1,
    color: '#D97706',
    category: 'Chuyên ngành',
  },
  {
    id: '5',
    name: 'Mạng máy tính',
    code: 'INT1319',
    credits: 3,
    instructor: 'PGS.TS. Phạm Văn Cường',
    schedule: 'Thứ 5 (09:45 - 12:00)',
    room: 'P.305-A3 (Hà Đông)',
    icon: 'network',
    lessons: 22,
    completedLessons: 22,
    progress: 1.0,
    color: '#0891B2',
    category: 'Cơ sở ngành',
  },
  {
    id: '6',
    name: 'Nhập môn Trí tuệ nhân tạo',
    code: 'INT13145',
    credits: 3,
    instructor: 'TS. Vũ Tất Thắng',
    schedule: 'Thứ 7 (07:00 - 09:30)',
    room: 'P.502-A2 (Hà Đông)',
    icon: 'ai',
    lessons: 28,
    completedLessons: 14,
    progress: 0.5,
    color: '#2563EB',
    category: 'Chuyên ngành',
  },
];

export const getStats = (courses: Course[], assignments: Assignment[]): StatItem[] => {
  const totalCourses = courses.length;
  const totalAssignments = assignments.length;
  const completedCourses = courses.filter((c) => c.progress >= 1.0).length;

  return [
    {
      id: 'courses',
      icon: 'books',
      value: totalCourses,
      label: 'Tổng môn học',
      subLabel: 'Học kỳ I',
      type: 'courses',
    },
    {
      id: 'assignments',
      icon: 'task',
      value: totalAssignments,
      label: 'Số bài tập',
      subLabel: 'Cần hoàn thành',
      type: 'assignments',
    },
    {
      id: 'completed',
      icon: 'check',
      value: completedCourses,
      label: 'Đã hoàn thành',
      subLabel: 'Tiến độ 100%',
      type: 'completed',
    },
  ];
};

export const STATS: StatItem[] = [
  { id: '1', icon: 'books', value: 6, label: 'Môn học', type: 'courses' },
  { id: '2', icon: 'task', value: 12, label: 'Bài tập', type: 'assignments' },
  { id: '3', icon: 'check', value: 2, label: 'Hoàn thành', type: 'completed' },
];

export const ASSIGNMENTS: Assignment[] = [
  {
    id: 'a1',
    courseName: 'Lập trình React Native',
    courseCode: 'INT1434',
    title: 'Bài tập thực hành 01: Dựng giao diện Quản lý Sinh viên',
    dueDate: '23:59 • 05/10/2026',
    status: 'pending',
  },
  {
    id: 'a2',
    courseName: 'Lập trình React Native',
    courseCode: 'INT1434',
    title: 'Bài tập 02: Xử lý State & Navigation',
    dueDate: '23:59 • 12/10/2026',
    status: 'pending',
  },
  {
    id: 'a3',
    courseName: 'Cơ sở dữ liệu',
    courseCode: 'INT1154',
    title: 'Bài tập lớn: Thiết kế CSDL Quản lý Thư viện',
    dueDate: '23:59 • 20/09/2026',
    status: 'graded',
    score: '9.5 / 10',
  },
  {
    id: 'a4',
    courseName: 'Cơ sở dữ liệu',
    courseCode: 'INT1154',
    title: 'Truy vấn SQL nâng cao với Stored Procedure',
    dueDate: '23:59 • 15/09/2026',
    status: 'graded',
    score: '10 / 10',
  },
  {
    id: 'a5',
    courseName: 'Cấu trúc dữ liệu & GT',
    courseCode: 'INT1340',
    title: 'Cài đặt Cây nhị phân tìm kiếm (BST) & Cân bằng AVL',
    dueDate: '23:59 • 08/10/2026',
    status: 'pending',
  },
  {
    id: 'a6',
    courseName: 'Cấu trúc dữ liệu & GT',
    courseCode: 'INT1340',
    title: 'Thuật toán đồ thị: Dijkstra & Kruskal',
    dueDate: '23:59 • 16/10/2026',
    status: 'pending',
  },
  {
    id: 'a7',
    courseName: 'Lập trình Java nâng cao',
    courseCode: 'INT1332',
    title: 'Bài thực hành 1: Thiết kế giao diện với JavaFX',
    dueDate: '23:59 • 09/10/2026',
    status: 'pending',
  },
  {
    id: 'a8',
    courseName: 'Mạng máy tính',
    courseCode: 'INT1319',
    title: 'Báo cáo cấu hình mạng LAN với Cisco Packet Tracer',
    dueDate: '23:59 • 18/09/2026',
    status: 'graded',
    score: '9.0 / 10',
  },
  {
    id: 'a9',
    courseName: 'Mạng máy tính',
    courseCode: 'INT1319',
    title: 'Phân tích gói tin TCP/IP với Wireshark',
    dueDate: '23:59 • 25/09/2026',
    status: 'submitted',
  },
  {
    id: 'a10',
    courseName: 'Nhập môn Trí tuệ nhân tạo',
    courseCode: 'INT13145',
    title: 'Thuật toán tìm kiếm A* và Minimax cho trò chơi Caro',
    dueDate: '23:59 • 11/10/2026',
    status: 'pending',
  },
  {
    id: 'a11',
    courseName: 'Lập trình React Native',
    courseCode: 'INT1434',
    title: 'Mini-Project: Ứng dụng Quản lý Chi tiêu',
    dueDate: '23:59 • 25/10/2026',
    status: 'pending',
  },
  {
    id: 'a12',
    courseName: 'Nhập môn Trí tuệ nhân tạo',
    courseCode: 'INT13145',
    title: 'Phân loại ảnh đơn giản với mô hình Perceptron',
    dueDate: '23:59 • 30/10/2026',
    status: 'pending',
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Nhắc nhở nộp bài tập lớn React Native',
    content: 'Hạn chót nộp Bài tập thực hành 01 (Quản lý Sinh viên) vào 23:59 Chủ Nhật tuần này.',
    time: '15 phút trước',
    read: false,
    type: 'urgent',
  },
  {
    id: 'n2',
    title: 'Đã có điểm môn Cơ sở dữ liệu',
    content: 'Thầy Hoàng Xuân Dậu đã công bố điểm Bài tập lớn: 9.5/10.',
    time: '2 giờ trước',
    read: false,
    type: 'grade',
  },
  {
    id: 'n3',
    title: 'Lịch thi kết thúc học phần',
    content: 'Phòng Đào tạo PTIT đã cập nhật lịch thi chính thức Học kỳ I.',
    time: '1 ngày trước',
    read: true,
    type: 'info',
  },
];

export const NAV: NavItem[] = [
  { id: 'home', icon: 'home', label: 'Trang chủ' },
  { id: 'course', icon: 'books', label: 'Môn học' },
  { id: 'task', icon: 'task', label: 'Bài tập', badge: 7 },
  { id: 'profile', icon: 'user', label: 'Cá nhân' },
];
